# Cloud Build configuration for Staging environment deployment
# This file is triggered by GitHub Actions after main branch merges
# It references secrets from Google Secret Manager (created manually by you)

steps:
  # Deploy to Cloud Run - Staging Environment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-staging'
    args:
      - 'run'
      - 'deploy'
      - 'api-best-shot-staging'  # Staging service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/api-best-shot:staging-${COMMIT_SHA}'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900s'  # 15 minutes timeout
      - '--max-instances'
      - '5'     # Lower than production (10)
      - '--min-instances'
      - '0'     # Scale to zero when not in use
      # Reference secrets from Secret Manager (NO creation/updates)
      - '--update-secrets=DB_STRING_CONNECTION=db-connection-staging:latest'
      - '--update-secrets=JWT_SECRET=jwt-secret:latest'
      - '--update-secrets=SENTRY_DSN=sentry-dsn:latest'
      - '--update-secrets=AWS_ACCESS_KEY_ID=aws-access-key:latest'
      - '--update-secrets=AWS_SECRET_ACCESS_KEY=aws-secret-key:latest'
      - '--update-secrets=INTERNAL_SERVICE_TOKEN=internal-service-token:latest'
      # Environment variables (non-sensitive)
      - '--update-env-vars=NODE_ENV=staging'
      - '--update-env-vars=PORT=8080'
      - '--update-env-vars=API_VERSION=v2'
      - '--update-env-vars=AWS_REGION=us-east-1'
      - '--update-env-vars=AWS_BUCKET_NAME=best-shot-staging'
      - '--update-env-vars=AWS_CLOUDFRONT_URL=https://staging.cdn.best-shot.com'
      - '--update-env-vars=API_DOMAIN=https://api-best-shot-staging-<hash>.a.run.app'
      - '--update-env-vars=ACCESS_CONTROL_ALLOW_ORIGIN=https://staging.best-shot.com'
      - '--update-env-vars=MEMBER_PUBLIC_ID_COOKIE=member_public_id_staging'
      # Service account (if needed)
      # - '--service-account=api-best-shot-staging@$PROJECT_ID.iam.gserviceaccount.com'

  # Tag the deployment for tracking
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'add-labels'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'api-best-shot-staging'
      - '--region=us-east1'
      - '--update-labels=environment=staging,commit=${SHORT_SHA},branch=${BRANCH_NAME},deployed=${_DEPLOY_TIME}'
    waitFor: ['deploy-staging']

# Build configuration
options:
  # Use a powerful machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Log to Cloud Logging
  logging: CLOUD_LOGGING_ONLY
  # Dynamic substitutions
  dynamicSubstitutions: true
  # Environment variables for the build
  env:
    - 'COMMIT_SHA=${COMMIT_SHA}'
    - 'SHORT_SHA=${SHORT_SHA}'
    - 'BRANCH_NAME=${BRANCH_NAME}'
    - '_DEPLOY_TIME=${_DEPLOY_TIME}'

# Substitutions (provided by GitHub Actions)
substitutions:
  _DEPLOY_TIME: '${_DEPLOY_TIME}'

# Timeout for entire build and deployment
timeout: '1200s'  # 20 minutes total

# Note: This configuration assumes the following secrets exist in Secret Manager:
# - db-connection-staging (Supabase staging connection string)
# - jwt-secret (JWT signing secret)
# - sentry-dsn (Sentry error tracking)
# - aws-access-key (AWS access key ID)
# - aws-secret-key (AWS secret access key)
# - internal-service-token (Internal API token)
#
# These secrets must be created manually in Google Cloud Console
# to avoid any risk of overwriting existing secrets.