services:
  env-setup:
    build:
      context: .
      dockerfile: Dockerfile.env-setup
    container_name: bestshot_env_setup
    volumes:
      - .:/app
    command: sh -c "chmod +x ./scripts/setup.sh && ./scripts/setup.sh"

  postgres:
    image: postgres:15
    container_name: bestshot_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bestshot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
    depends_on:
      - env-setup

volumes:
  postgres_data:

networks:
  bestshot_network:
    driver: bridge