
services:
  postgres:
    image: postgres:15
    container_name: bestshot_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: bestshot_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bestshot_network

volumes:
  postgres_data:

networks:
  bestshot_network:
    driver: bridge 