services:
  env-setup:
    build:
      context: .
      dockerfile: Dockerfile.env-setup
    container_name: bestshot_env_setup
    volumes:
      - .:/app
    
    command: sh -c "chmod +x ./scripts/setup.sh && ./scripts/setup.sh"
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.env"]
      interval: 10s
      timeout: 5s
      retries: 3
    profiles:
      - setup

  postgres:
    image: postgres:15
    container_name: bestshot_db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bestshot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]

volumes:
  postgres_data:

networks:
  bestshot_network:
    driver: bridge
