services:
  postgres:
    image: postgres:15
    container_name: bestshot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bestshot
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bestshot_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d bestshot']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  bestshot_network:
    driver: bridge
