services:
  setup:
    image: alpine:3.18
    container_name: bestshot_setup
    volumes:
      - ./scripts/setup:/setup
    working_dir: /setup
    command: sh -c "chmod +x main.sh && ./main.sh ${SETUP_MODE:-initial}"
    environment:
      - SETUP_MODE=${SETUP_MODE:-initial}
    profiles:
      - initial-setup
      - update-setup

  postgres:
    image: postgres:15
    container_name: bestshot_db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bestshot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]

volumes:
  postgres_data:

networks:
  bestshot_network:
    driver: bridge
