packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - miniflare@4.20260708.0
  - wrangler@4.109.0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
