import { DB_InsertTeam, T_Team } from '@/domains/team/schema';
import db from '@/services/database';
import { fetchAndStoreAssetFromApiNew } from '@/utils';
import axios from 'axios';
import { eq } from 'drizzle-orm';
import { IApiProviderV2 } from '../../interface';
import { API_SofaScoreStandings } from './typing';
const SOFA_TEAM_LOGO_URL = 'https://img.sofascore.com/api/v1/team/:id/image/';

export const SofascoreTeams: IApiProviderV2['teams'] = {
  fetchTeamsFromStandings: async (baseUrl: string) => {
    const response = await axios.get(`${baseUrl}/standings/total`);

    return response.data as API_SofaScoreStandings;
  },
  mapTeamsFromStandings: async (data: API_SofaScoreStandings, provider) => {
    const standings = data?.standings;
    const groupOfTeams = standings.map(groupOfTeams => groupOfTeams.rows);
    const allTournamentTeams = groupOfTeams.flat();

    const promises = allTournamentTeams.map(async ({ team }) => {
      const badge = await SofascoreTeams.fetchAndStoreLogo({
        filename: `team-${provider}-${team.id}`,
        logoUrl: SOFA_TEAM_LOGO_URL.replace(':id', String(team.id)),
      });
      return {
        name: team.name,
        externalId: String(team.id),
        shortName: team.nameCode,
        badge,
        provider: 'sofa',
      } satisfies DB_InsertTeam;
    });

    return Promise.all(promises);
  },
  fetchAndStoreLogo: async data => {
    const assetPath = await fetchAndStoreAssetFromApiNew(data);

    return assetPath ? `https://${process.env['AWS_CLOUDFRONT_URL']}/${assetPath}` : '';
  },
  createOnDatabase: async teams =>
    await db.insert(T_Team).values(teams).onConflictDoNothing().returning(),
  updateOnDatabase: async teams => {
    return await db.transaction(async tx => {
      for (const team of teams) {
        return await tx
          .update(T_Team)
          .set(team)
          .where(eq(T_Team.externalId, team.externalId))
          .returning();
      }
    });
  },
  fetchTeamsFromAvailableRounds: async (allAvailableRounds, baseUrl) => {
    const allTeams = allAvailableRounds.map(async round => {
      let urlToFetch = '';

      if (round.type === 'knockout') {
        urlToFetch = `${baseUrl}/events/round/${round.order}/slug/${round.slug}`;
      }

      if (round.type === 'season') {
        urlToFetch = `${baseUrl}/season/rounds/${round.order}`;
      }

      const response = await axios.get(urlToFetch);

      return response.data;
    });

    return Promise.all(allTeams);
  },
  mapTeamsFromAvailableRounds: async (data, provider) => {
    const round = data[0].events;

    const promises = round.map(async (game: any) => {
      const homeTeam = game.homeTeam;
      const homeTeamBadge = await SofascoreTeams.fetchAndStoreLogo({
        filename: `team-${provider}-${homeTeam.id}`,
        logoUrl: SOFA_TEAM_LOGO_URL.replace(':id', String(homeTeam.id)),
      });

      const awayTeam = game.awayTeam;
      const awayTeamBadge = await SofascoreTeams.fetchAndStoreLogo({
        filename: `team-${provider}-${awayTeam.id}`,
        logoUrl: SOFA_TEAM_LOGO_URL.replace(':id', String(awayTeam.id)),
      });

      return [
        {
          name: homeTeam.name,
          externalId: String(homeTeam.id),
          shortName: homeTeam.nameCode,
          badge: homeTeamBadge,
          provider: 'sofa',
        } satisfies DB_InsertTeam,
        {
          name: awayTeam.name,
          externalId: String(awayTeam.id),
          shortName: awayTeam.nameCode,
          badge: awayTeamBadge,
          provider: 'sofa',
        } satisfies DB_InsertTeam,
      ];
    });

    return Promise.all(promises);
  },
};

const fakeData = [
  {
    events: [
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'FZobsAoRb',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Academia Puerto Cabello',
          slug: 'academia-puerto-cabello',
          shortName: 'Puerto Cabello',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 4051,
          nameCode: 'APC',
          national: false,
          type: 0,
          id: 230725,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#000242',
            secondary: '#fe5c03',
            text: '#fe5c03',
          },
          fieldTranslations: {
            nameTranslation: {
              ar: 'أكاديميا بويرتو كابيو',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Metropolitanos',
          slug: 'metropolitanos',
          shortName: 'Metropolitanos',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 4700,
          nameCode: 'MET',
          disabled: false,
          national: false,
          type: 0,
          id: 162480,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#380e56',
            secondary: '#cb1158',
            text: '#cb1158',
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252447,
        startTimestamp: 1741118400,
        slug: 'academia-puerto-cabello-metropolitanos',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'FzcsMDo',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Deportivo La Guaira',
          slug: 'deportivo-la-guaira',
          shortName: 'La Guaira',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 3371,
          nameCode: 'DLG',
          national: false,
          type: 0,
          id: 36437,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ff6521',
            secondary: '#056ff6',
            text: '#056ff6',
          },
          fieldTranslations: {
            nameTranslation: {
              ar: 'ديپورتيڢو لاجويرا',
              ru: 'Депортиво Ла Гуайра',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Caracas F.C.',
          slug: 'caracas-fc',
          shortName: 'Caracas',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 6725,
          nameCode: 'CAR',
          disabled: false,
          national: false,
          type: 0,
          id: 6230,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#cc0000',
            secondary: '#ffffff',
            text: '#ffffff',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Каракас ФК',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252448,
        startTimestamp: 1741118400,
        slug: 'deportivo-la-guaira-caracasc',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'cxcsfxc',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Junior Barranquilla',
          slug: 'junior-barranquilla',
          shortName: 'Junior Barranquilla',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 42937,
          nameCode: 'JUN',
          disabled: false,
          national: false,
          type: 0,
          id: 6105,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#cc0000',
            secondary: '#ffffff',
            text: '#ffffff',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Атлетико Джуниор',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'América de Cali',
          slug: 'america-de-cali',
          shortName: 'América',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 33122,
          nameCode: 'AME',
          disabled: false,
          national: false,
          type: 0,
          id: 6102,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ff0000',
            secondary: '#ff0000',
            text: '#ff0000',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Америка Кали',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252438,
        startTimestamp: 1741118400,
        slug: 'junior-barranquilla-america-de-cali',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'YucskvEc',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Sportivo Luqueño',
          slug: 'sportivo-luqueno',
          shortName: 'Sportivo Luqueño',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 8747,
          nameCode: 'LUQ',
          disabled: false,
          national: false,
          type: 0,
          id: 5998,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#ffffff',
            text: '#ffffff',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Спортиво Лукеньо',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Sportivo Ameliano',
          slug: 'sportivo-ameliano',
          shortName: 'Sportivo Ameliano',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 8751,
          nameCode: 'SPO',
          national: false,
          type: 0,
          id: 323510,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#00008b',
            text: '#00008b',
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252441,
        startTimestamp: 1741118400,
        slug: 'sportivo-ameliano-sportivo-luqueno',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'dnbsHac',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Unión Española',
          slug: 'union-espanola',
          shortName: 'Unión Española',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 6597,
          nameCode: 'ESP',
          national: false,
          type: 0,
          id: 3153,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ff0000',
            secondary: '#ffff00',
            text: '#ffff00',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Юнион Эспаньола',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Everton de Viña del Mar',
          slug: 'everton-de-vina-del-mar',
          shortName: 'Everton',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 6153,
          nameCode: 'EVT',
          national: false,
          type: 0,
          id: 5032,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#000088',
            secondary: '#ffff00',
            text: '#ffff00',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Эвертон Вина Дел Мар',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252437,
        startTimestamp: 1741118400,
        slug: 'everton-de-vina-del-mar-union-espanola',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'bnbshnb',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Universidad Católica',
          slug: 'universidad-catolica',
          shortName: 'Universidad Católica',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 16985,
          nameCode: 'UC',
          disabled: false,
          national: false,
          type: 0,
          id: 3151,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#ffffff',
            text: '#ffffff',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Универсидад Католика',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Palestino',
          slug: 'palestino',
          shortName: 'Palestino',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 14329,
          nameCode: 'PAL',
          national: false,
          type: 0,
          id: 3157,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#000000',
            text: '#000000',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Палестино',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252436,
        startTimestamp: 1741118400,
        slug: 'palestino-universidad-catolica',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'ZecsRNi',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Universidad Católica del Ecuador',
          slug: 'universidad-catolica-del-ecuador',
          shortName: 'Universidad Católica',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 10680,
          nameCode: 'UNI',
          national: false,
          type: 0,
          id: 21942,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#4bacd2',
            secondary: '#222226',
            text: '#222226',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Универсидад Католика',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Aucas',
          slug: 'aucas',
          shortName: 'Aucas',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 8563,
          nameCode: 'SDA',
          disabled: false,
          national: false,
          type: 0,
          id: 5249,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#d4252a',
            secondary: '#ffdd00',
            text: '#ffdd00',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Аукас',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252440,
        startTimestamp: 1741118400,
        slug: 'universidad-catolica-del-ecuador-aucas',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'aeusHlhc',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'FC Universitario de Vinto',
          slug: 'fc-universitario-de-vinto',
          shortName: 'Univ. de Vinto',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 3734,
          nameCode: 'UVI',
          national: false,
          type: 0,
          id: 268082,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#e50412',
            text: '#e50412',
          },
        },
        awayTeam: {
          name: 'Nacional Potosí',
          slug: 'nacional-potosi',
          shortName: 'Nacional Potosí',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 8742,
          nameCode: 'CNP',
          national: false,
          type: 0,
          id: 47700,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#ffffff',
            text: '#ffffff',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Насьональ Потоси',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13259683,
        startTimestamp: 1741125600,
        slug: 'fc-universitario-de-vinto-nacional-potosi',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'bWshlJc',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Asociación Deportiva Tarma',
          slug: 'asociacion-deportiva-tarma',
          shortName: 'ADT',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 4630,
          nameCode: 'ASO',
          disabled: false,
          national: false,
          type: 0,
          id: 335557,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#374df5',
            secondary: '#374df5',
            text: '#ffffff',
          },
        },
        awayTeam: {
          name: 'Cienciano',
          slug: 'cienciano',
          shortName: 'Cienciano',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 6229,
          nameCode: 'CIE',
          national: false,
          type: 0,
          id: 2301,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ff0000',
            secondary: '#ff0000',
            text: '#ff0000',
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252443,
        startTimestamp: 1741140000,
        slug: 'asociacion-deportiva-tarma-cienciano',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'OOisozn',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Club Aurora',
          slug: 'club-aurora',
          shortName: 'Club Aurora',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 8212,
          nameCode: 'AUR',
          disabled: false,
          national: false,
          type: 0,
          id: 33714,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#33ccff',
            secondary: '#66ccff',
            text: '#66ccff',
          },
          fieldTranslations: {
            nameTranslation: {
              ar: 'كلوب اورورا',
              ru: 'Клуб Аврора',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'CD San José',
          slug: 'cd-san-jose',
          shortName: 'San José',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 280,
          nameCode: 'SJO',
          disabled: false,
          national: false,
          type: 0,
          id: 21989,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#000066',
            text: '#000066',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Сан-Хосе де Оруро',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13259682,
        startTimestamp: 1741212000,
        slug: 'club-aurora-cd-san-jose',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'Pobskak',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Racing de Montevideo',
          slug: 'racing-de-montevideo',
          shortName: 'Racing',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 7277,
          nameCode: 'RCM',
          national: false,
          type: 0,
          id: 25010,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#339900',
            secondary: '#ffffff',
            text: '#ffffff',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Расинг Клуб Монтевидео',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Montevideo Wanderers',
          slug: 'montevideo-wanderers',
          shortName: 'Wanderers',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 3699,
          nameCode: 'WAN',
          disabled: false,
          national: false,
          type: 0,
          id: 3240,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#000000',
            text: '#000000',
          },
          fieldTranslations: {
            nameTranslation: {
              ar: 'مونتيفيديو وانديررز',
              ru: 'Монтевидео Уондерерз',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252445,
        startTimestamp: 1741212000,
        slug: 'racing-de-montevideo-montevideo-wanderers',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'rxcstxc',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Once Caldas',
          slug: 'once-caldas',
          shortName: 'Once Caldas',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 14355,
          nameCode: 'OC',
          national: false,
          type: 0,
          id: 6118,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#ffffff',
            text: '#ffffff',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Онсе Кальдас',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Millonarios',
          slug: 'millonarios',
          shortName: 'Millonarios',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 57307,
          nameCode: 'MIL',
          disabled: false,
          national: false,
          type: 0,
          id: 6117,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#0000cc',
            secondary: '#0000cc',
            text: '#0000cc',
          },
          fieldTranslations: {
            nameTranslation: {
              ar: 'النادى الرياضي ميلوناريوس',
              ru: 'ФК Мильонариос',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13262221,
        startTimestamp: 1741221000,
        slug: 'once-caldas-millonarios',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'BZdbsAalc',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Mushuc Runa',
          slug: 'mushuc-runa',
          shortName: 'Mushuc Runa',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 3927,
          nameCode: 'MUR',
          national: false,
          type: 0,
          id: 134976,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#00e100',
            secondary: '#009933',
            text: '#009933',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Мушук Руна',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Orense SC',
          slug: 'orense-sc',
          shortName: 'Orense',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 4057,
          nameCode: 'ORE',
          national: false,
          type: 0,
          id: 277525,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#7cfc00',
            secondary: '#00009a',
            text: '#00009a',
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252439,
        startTimestamp: 1741226400,
        slug: 'orense-sc-mushuc-runa',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'Dobsjak',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Cerro Largo',
          slug: 'cerro-largo',
          shortName: 'Cerro Largo',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 4154,
          nameCode: 'CLA',
          national: false,
          type: 0,
          id: 25009,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#0000ff',
            text: '#0000ff',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Серро Ларго ФК',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Danubio',
          slug: 'danubio',
          shortName: 'Danubio',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 6525,
          nameCode: 'DAN',
          disabled: false,
          national: false,
          type: 0,
          id: 3228,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#000000',
            text: '#000000',
          },
          fieldTranslations: {
            nameTranslation: {
              ar: 'نادي دانوبيو',
              ru: 'Данубио',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252446,
        startTimestamp: 1741298400,
        slug: 'cerro-largo-danubio',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'RucsUuc',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Guaraní',
          slug: 'guarani',
          shortName: 'Guaraní',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 11577,
          nameCode: 'GUA',
          national: false,
          type: 0,
          id: 5994,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#000000',
            secondary: '#ffff33',
            text: '#ffff33',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Клуб Гуарани',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'CS 2 de Mayo',
          slug: 'cs-2-de-mayo',
          shortName: '2 de Mayo',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 6225,
          nameCode: 'MAY',
          national: false,
          type: 0,
          id: 5992,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#0000cc',
            secondary: '#ffffff',
            text: '#ffffff',
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252442,
        startTimestamp: 1741298400,
        slug: 'guarani-cs-2-de-mayo',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'kAAsNanc',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Club Atlético Grau',
          slug: 'club-atletico-grau',
          shortName: 'Atlético Grau',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 5587,
          nameCode: 'CAG',
          national: false,
          type: 0,
          id: 282538,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#ffffff',
            secondary: '#ff0000',
            text: '#ff0000',
          },
        },
        awayTeam: {
          name: 'Cusco FC',
          slug: 'cusco-fc',
          shortName: 'Cusco',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 6023,
          nameCode: 'CUS',
          national: false,
          type: 0,
          id: 63760,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#00ffff',
            secondary: '#33ffff',
            text: '#33ffff',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Реал Гарсиласо',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13252444,
        startTimestamp: 1741307400,
        slug: 'club-atletico-grau-cusco-fc',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
      {
        tournament: {
          name: 'CONMEBOL Sudamericana, Qualification',
          slug: 'copa-sudamericana-qualification',
          category: {
            name: 'South America',
            slug: 'south-america',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1470,
            flag: 'south-america',
          },
          uniqueTournament: {
            name: 'CONMEBOL Sudamericana',
            slug: 'conmebol-sudamericana',
            primaryColorHex: '#e3c000',
            secondaryColorHex: '#13489c',
            category: {
              name: 'South America',
              slug: 'south-america',
              sport: {
                name: 'Football',
                slug: 'football',
                id: 1,
              },
              id: 1470,
              flag: 'south-america',
            },
            userCount: 135282,
            hasPerformanceGraphFeature: false,
            id: 480,
            hasEventPlayerStatistics: true,
            displayInverseHomeAwayTeams: false,
          },
          priority: 469,
          isGroup: false,
          isLive: false,
          id: 91417,
        },
        season: {
          name: 'CONMEBOL Sudamericana 2025',
          year: '2025',
          editor: false,
          id: 70070,
        },
        roundInfo: {
          round: 1,
          name: 'Qualification Round 1',
          slug: 'qualification-round-1',
        },
        customId: 'ZecsRNi',
        status: {
          code: 0,
          description: 'Not started',
          type: 'notstarted',
        },
        homeTeam: {
          name: 'Universidad Católica del Ecuador',
          slug: 'universidad-catolica-del-ecuador',
          shortName: 'Universidad Católica',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 10680,
          nameCode: 'UNI',
          national: false,
          type: 0,
          id: 21942,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#4bacd2',
            secondary: '#222226',
            text: '#222226',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Универсидад Католика',
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: 'Aucas',
          slug: 'aucas',
          shortName: 'Aucas',
          gender: 'M',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          userCount: 8563,
          nameCode: 'SDA',
          disabled: false,
          national: false,
          type: 0,
          id: 5249,
          entityType: 'team',
          subTeams: [],
          teamColors: {
            primary: '#d4252a',
            secondary: '#ffdd00',
            text: '#ffdd00',
          },
          fieldTranslations: {
            nameTranslation: {
              ru: 'Аукас',
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {},
        awayScore: {},
        time: {},
        changes: {
          changeTimestamp: 0,
        },
        hasGlobalHighlights: false,
        crowdsourcingDataDisplayEnabled: false,
        id: 13264039,
        startTimestamp: 1741312800,
        slug: 'universidad-catolica-del-ecuador-aucas',
        finalResultOnly: false,
        feedLocked: false,
        isEditor: false,
      },
    ],
    hasNextPage: false,
  },
];
