name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: api-best-shot-demo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Enable Yarn 3
        run: corepack enable && corepack prepare yarn@3.8.7 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type check
        run: yarn compile

      - name: Test build
        run: yarn build

      - name: Configure Docker for gcr.io
        run: gcloud auth configure-docker --quiet

      - name: Pull cache image
        run: docker pull gcr.io/api-best-shot-demo/api-best-shot-demo:latest || true

      - name: Build Docker image
        run: |
          docker build \
            --cache-from gcr.io/api-best-shot-demo/api-best-shot-demo:latest \
            -t gcr.io/api-best-shot-demo/api-best-shot-demo:${{ github.sha }} \
            -t gcr.io/api-best-shot-demo/api-best-shot-demo:latest \
            .

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/api-best-shot-demo/api-best-shot-demo:${{ github.sha }}
          docker push gcr.io/api-best-shot-demo/api-best-shot-demo:latest

      - name: Trigger Cloud Build deployment
        run: |
          gcloud builds submit --no-source --config=cloudbuild.yaml --substitutions=COMMIT_SHA=${{ github.sha }}