name: Seed Demo Database

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm seeding the demo database'
        required: true
        default: 'no'

jobs:
  seed-demo-db:
    if: ${{ github.event.inputs.confirmation == 'yes' }}
    runs-on: ubuntu-latest
    environment: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Print DB environment variables
        run: |
          echo "DB_HOST=$DB_HOST"
          echo "DB_PORT=$DB_PORT"
          echo "DB_USER=$DB_USER"
          echo "DB_NAME=$DB_NAME"
          echo "DB_PASSWORD is set? [${#DB_PASSWORD} chars]"
        env:
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ vars.DB_NAME }}

      - name: Seed Demo Database
        run: yarn tsx scripts/run-seeds.ts
        env:
          NODE_ENV: demo
          ENV_PATH: .env.demo
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ vars.DB_NAME }}
