name: Seed Demo Database

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm seeding the demo database'
        required: true
        default: 'no'

jobs:
  seed-demo-db:
    if: ${{ github.event.inputs.confirmation == 'yes' }}
    runs-on: ubuntu-latest
    environment: demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Debug Connection Info
        run: |
          echo "Attempting to connect to database with:"
          echo "NODE_ENV: demo"
          echo "DB_HOST: ${{ vars.DB_HOST }}"
          echo "DB_PORT: ${{ vars.DB_PORT }}"
          echo "DB_USER: ${{ vars.DB_USER }}"
          echo "DB_NAME: ${{ vars.DB_NAME }}"
          echo "DB_PASSWORD: ${{ vars.DB_PASSWORD }}"

      - name: Seed Demo Database
        env:
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ vars.DB_PASSWORD }}
          DB_NAME: ${{ vars.DB_NAME }}
          NODE_ENV: demo
        run: |
          yarn db:seed
