name: Seed Demo Database

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm seeding the demo database'
        required: true
        default: 'no'

jobs:
  seed-demo-db:
    if: ${{ github.event.inputs.confirmation == 'yes' }}
    runs-on: ubuntu-latest
    environment: demo
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check API Health
        env:
          API_URL: ${{ vars.API_URL || 'https://api-best-shot-demo.mariobrusarosco.com' }}
        run: |
          echo "🔍 Checking API health..."
          response=$(curl -s -w "\n%{http_code}" "$API_URL/api/v1/admin/health")

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)

          echo "Health check response: $body"
          echo "HTTP Status: $http_code"

          if [ "$http_code" -eq 200 ]; then
            echo "✅ API is healthy and ready!"
          else
            echo "❌ API health check failed with status $http_code"
            exit 1
          fi

      - name: Seed Demo Database via API
        env:
          API_URL: ${{ vars.API_URL || 'https://api-best-shot-demo.mariobrusarosco.com' }}
          SEED_DB_TOKEN: ${{ secrets.SEED_DB_TOKEN }}
        run: |
          echo "🌱 Calling seeding API endpoint with authentication..."
          response=$(curl -s -w "\n%{http_code}" -X POST "$API_URL/api/v1/admin/seed" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $SEED_DB_TOKEN")

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)

          echo "Response: $body"
          echo "HTTP Status: $http_code"

          if [ "$http_code" -eq 200 ]; then
            echo "✅ Database seeded successfully!"
          else
            echo "❌ Seeding failed with status $http_code"
            exit 1
          fi
        timeout-minutes: 5
