name: Deploy to Cloud Run

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PROJECT_ID: api-best-shot-staging
  REGION: us-east1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4
      
      # Enable corepack FIRST for Yarn 3
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@3.8.7 --activate
      
      # Setup Node.js with caching (after corepack)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      
      # Install dependencies and run tests
      - name: Install & Test
        run: |
          yarn install --immutable
          yarn lint
          yarn compile
          yarn test
      
      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_STAGING }}
      
      # Deploy to Cloud Run with source deployment (all optimizations enabled!)
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: api-best-shot-staging
          source: .
          region: ${{ env.REGION }}
          project: ${{ env.PROJECT_ID }}
          flags: |
            --cpu=2
            --memory=2Gi
            --min-instances=0
            --max-instances=10
            --port=8080
            --allow-unauthenticated
          env_vars: |
            NODE_ENV=staging
            PORT=8080