name: Deploy to Cloud Run

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PROJECT_ID: api-best-shot-staging
  REGION: us-east1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4
      
      # Enable corepack FIRST for Yarn 4
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
      
      # Setup Node.js with caching (after corepack)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      
      # Install dependencies and run tests
      - name: Install & Test
        run: |
          yarn install --immutable
          yarn lint
          yarn compile
          yarn test
      
      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_STAGING }}
      
      # Deploy to Cloud Run with source deployment (all optimizations enabled!)
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: api-best-shot-staging
          source: .
          region: ${{ env.REGION }}
          project: ${{ env.PROJECT_ID }}
          flags: |
            --cpu=2
            --memory=2Gi
            --min-instances=0
            --max-instances=10
            --port=8080
            --allow-unauthenticated
            --tag=latest
          env_vars: |
            NODE_ENV=staging
            API_DOMAIN=api-best-shot-staging-415034926128.us-east1.run.app
            API_VERSION=/v2
            AWS_REGION=us-east-1
            MEMBER_PUBLIC_ID_COOKIE=best-shot-auth
            ACCESS_CONTROL_ALLOW_ORIGIN=https://best-shot-staging.mariobrusarosco.com
            AWS_ACCOUNT_ID=905418297381
            AWS_BUCKET_NAME=assets.mariobrusarosco.com
            AWS_CLOUDFRONT_URL=dk57aekjop3j1.cloudfront.net
          secrets: |
            JWT_SECRET=jwt-secret:latest
            DB_STRING_CONNECTION=db-connection-staging:latest
            AWS_ACCESS_KEY_ID=aws-access-key:latest
            AWS_SECRET_ACCESS_KEY=aws-secret-key:latest
            SENTRY_DSN=sentry-dsn:latest
            INTERNAL_SERVICE_TOKEN=internal-service-token:latest