name: Updating Tournament Matches on Database

on:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:

jobs:
  watch-for-matches:
    runs-on: ubuntu-latest

    steps:
      - name: Define Tournaments and Make API Calls
        env:
          COOKIE: ${{ secrets.API_COOKIE_DEMO }}
          TOURNAMENT_IDS: ${{ vars.TOURNAMENT_IDS_DEMO }}
        run: |
          echo "Raw TOURNAMENT_IDS: $TOURNAMENT_IDS"

          # Set comma as delimiter
          IFS=','

          # Loop over each tournament ID
          for TOURNAMENT in $TOURNAMENT_IDS
          do
            TOURNAMENT=$(echo "$TOURNAMENT" | xargs)
            echo "Processing tournament $TOURNAMENT"
            echo "{\"tournamentId\":\"$TOURNAMENT\"}"
            echo "${COOKIE}"

            TOURNAMENT=$(echo "$TOURNAMENT" | xargs)

            curl -X PATCH "https://api-best-shot-demo.mariobrusarosco.com/api/v1/data-provider/matches/" \
              -H "Content-Type: application/json" \
              -H "Cookie: ${COOKIE}" \
              -d "{\"tournamentId\":\"${TOURNAMENT}\"}"

            echo "Waiting 30 minutes before the next call..."
            sleep $((30 * 60))
          done
